# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EzZgBfaHt8X07gdSqvGkqmT4lAOTIxn_

#Day 9 Assignment 2

Name:- Ansari Mohammed Ali Nasim

Date:-11/09/2020

Purpose:- Python Essentials-Batch 7 Day 9 Assignment 2

Problem Statement:-Make a small generator program for returning
armstrong numbers in between 1-1000 in a generator object.
"""

def armstrong(size):
    for number in range(size):
        l = len(str(number))
        s = 0
        i = number
        while i > 0:
            no = i % 10
            s += no ** l
            i //= 10
        if number == s:
            yield number
        else:
            continue


print(list(armstrong(1000)))